### ISSUE TITLE
bootique-jooq-codegen

### ISSUE THREAD

**Issue by IRus** [bootique/bootique-jooq#5]
Module witch generates JOOQ classes from provided DataSources.

**Comment by andrus** [comment]
Does this idea belong in Bootique? Class generation happens during development. And Jooq has its own tools for it. (I just integrated their Maven plugin in bootique-jooq tests).

**Comment by IRus** [comment]
So idea was to create module, which can be used as cli tool for code-generation. Like in [this example](https://www.jooq.org/doc/3.10/manual/code-generation/codegen-configuration/), but in Bootique way.
